### ISSUE TITLE
Can not run in Google Colab

### ISSUE THREAD

**Issue by quangchien99** [ptran1203/traffic_sign_detection#1]
Hey bro, I'm totally impressed with your project. Therefore, i tried to run it in Google Colab to see your magic. 
However, in some final step, i can not run it.
Specifically is the prediction:
<img width="962" alt="Screen Shot 2020-12-16 at 09 00 24" src="https://user-images.githubusercontent.com/69864173/102295257-964ca780-3f7d-11eb-93da-bec4e1da4e75.png">

I got this error: 
<img width="943" alt="Screen Shot 2020-12-16 at 09 00 35" src="https://user-images.githubusercontent.com/69864173/102295307-a6fd1d80-3f7d-11eb-8c12-69b6728d61bc.png">
<img width="1054" alt="Screen Shot 2020-12-16 at 09 01 01" src="https://user-images.githubusercontent.com/69864173/102295323-ae242b80-3f7d-11eb-96f4-be59a079732b.png">

I really really want to run that, so can you fix it.
Or email me via: quangchiennnn@gmail.com
I hope to have your support

**Comment by ptran1203** [comment]
Hi @quangchien99, I thank you for your concern. I will check this issue and update the notebook

**Comment by ptran1203** [comment]
Hi Chien, This issue is fixed [here](https://github.com/ptran1203/traffic_sign_detection/commit/11ee65d5b494836113e6caf22af082fe192eabf7) and I updated the [notebook](https://github.com/ptran1203/traffic_sign_detection/blob/main/traffic_signs_detection.ipynb), please check again. Thank you :tada:

**Comment by quangchien99** [comment]
Thank you so muchhh! i got thisssss.
Amazingggggg
