### ISSUE TITLE
ASK ABOUT THE DATASET

### ISSUE THREAD

**Issue by NguyenKhacPhuc** [ptran1203/traffic_sign_detection#2]
Hello, I'm sorry but this is not a issue, i just want to ask you a little bit about the dataset, the bbox has 4 values and i wonder if it is xmin, y min, x max, y max or x, y and width height of the bbox? Please help me if you know.Thank You!

**Comment by ptran1203** [comment]
Hi Phuc, the box format is x, y, width, height
