### ISSUE TITLE
self.separate

### ISSUE THREAD

**Issue by sondo2503** [ptran1203/traffic_sign_detection#7]
https://github.com/ptran1203/traffic_sign_detection/blob/2dde05510699ecd2895017bc03285ca88a4d099f/prediction.py#L54-L58
Thanks for your sharing. I have a question about this function. I didn't see any "self.separate" in your __init__ function. Did you mean "self.separate_y" ?

**Comment by ptran1203** [comment]
It set [here](https://github.com/ptran1203/traffic_sign_detection/blob/2dde05510699ecd2895017bc03285ca88a4d099f/prediction.py#L73), Probably I have missed something, because the error did not occurred in runtime.

**Comment by sondo2503** [comment]
thanks for your reply
